import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alesandRegular = localFont({
  src: "./fonts/Alesand_Regular.ttf",
  variable: "--font-regular",
});

const alesandBold = localFont({
  src: "./fonts/Alesand_Bold.ttf",
  variable: "--font-bold",
});

const alesandExtraBold = localFont({
  src: "./fonts/Alesand_Extra_Bold.ttf",
  variable: "--font-extra-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alesandRegular.variable} ${alesandBold.variable} ${alesandExtraBold.variable} font-regular antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
